#! /bin/bash

# 该脚本生成一个cpp文件，包含最基本的代码

get_file_content()
{
cat << !FILE_CONTENT!
/*
 *
 */

#include <iostream>

using namespace std;

int main()
{
	return 0;
}
!FILE_CONTENT!
}

main()
{
	if [ "$#" = "0" ]; then
		file_name="main.cpp"
	else
		file_name=$1
	fi

	if [ -f $file_name ]; then
		echo $file_name is already exist, create file failed
		return 1
	fi

	get_file_content > $file_name
	vim $file_name

	return 0
}

main $@
